### ISSUE TITLE
Log4J dependency with Rocky Linux 9.1 

### ISSUE THREAD

**Issue by aeng-bas** [sbluhm/uyuni#100] opened 2023-05-03 13:41 UTC
### Problem description

Attempting to install on Rocky Linux 9.1 hits a dependency issue:

nothing provides log4j needed by spacewalk-taskomatic-4.4.17-220400.24.1.uyuni2.noarch

### Steps to reproduce

1. Fresh install of Rocky Linux 9.1
2. Run script https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/install9.sh

### Uyuni version

```bash
Uyuni-Server-release.noarch 2023.03-220400.207.1.uyuni2
```

### Additional information

To get around this:

`dnf config-manager --set-enabled devel`

Edit /etc/yum.repos.d/rocky-devel.repo so that under the [devel] section add the line: 

`includepkgs=log4j,log4j-slf4j`

**Comment by sbluhm** [comment] 2023-05-03 19:20
Found a package of mybatis on my local drive and installation works fine on AlmaLinux.

The issue is pretty interesting. AlmaLinux has log4j 2.17.1 in Appstream.
Rocky has the same version only in devel.
I am not sure where Red Hat has it.
So I guess the solution would be to supply log4j with the EL9 Uyuni repository

**Comment by sbluhm** [comment] 2023-05-03 19:47
It is now added to the Uyuni repo so I will close the issue. Please re-open if you still have this issue.
Note that atm, tomcat is not starting. Not sure why yet.

Thank you for raising this issue!

**Closed by sbluhm** 2023-05-03 19:47 UTC
Labels: bug

**Comment by sbluhm** [comment] 2023-05-05 11:38
fyi, tomcat starts again
